name: Min side
favicon: null
layout_spectrum: 0.2465
typography_spectrum: 0.2539489862974733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0b'
    - '#4a4a4a'
    - '#838383'
    - '#aeaeae'
    - '#dddddd'
  brandStrength: 0.5
  lightness: 0.2660486891400069
  saturation: 0.40154434740543365
  rhythmicContrast: 0.3238604662474245
purpose: []
