name: Min side
favicon: null
layout_spectrum: 0.2465
typography_spectrum: 0.2539489862974733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dae7f1'
    - '#988b84'
    - '#4a3a2b'
    - '#6f5a44'
    - '#e8c685'
  brandStrength: 0.5
  lightness: 0.2660486891400069
  saturation: 0.40154434740543365
  rhythmicContrast: 0.3238604662474245
purpose: []
